[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gixpy_etortorici"
version = "1.0"
authors = [
  { name="Teddy Tortorici", email="edward.tortorici@colorado.edu" },
]
description = "Transform GIWAXS images"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/etortorici/gixpyy"
Issues = "https://github.com/etortorici/gixpyy/issues"